eco/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView
from django.contrib.auth.views import logout_then_login, LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name ='index'),
    path('accounts/',include('django.contrib.auth.urls')),
    path('user/', include('user.urls'), name = 'user'),
    path('productos/', include('productos.urls'), name = 'productos'),
]

user/urls.py
from django.urls import path
from .views import GrafView,RegUserEntity,RegAdmin,RegEntity, ListEntity,HomeUserView,HomeUserView2,ListEntityUser, ProfileMunFormView, ProfileCopFormView, ProfilePuntFormView,post_estad_mu
from django.contrib.auth.decorators import login_required

urlpatterns = [
    ########################Home para Usuarios##########################################
    path('home/',login_required(HomeUserView2), name = 'home'),
    ######################Manejo de Usuarios###########################################
    path('crear_user/', login_required(RegUserEntity.as_view()) , name = 'crear_user'),
    path('crear_admin/', login_required(RegAdmin.as_view()),name = 'crear_admin'),
    #######################URLS entidades##########################################
    path('crear_entity/', login_required(RegEntity.as_view()) , name = 'crear_entity'),
    path('participantes/', login_required(ListEntity.as_view()), name = 'participantes'),
    path('entidades/',login_required(ListEntityUser.as_view()), name = 'entidades-user'),
    path('crear_mun/',login_required(ProfileMunFormView.as_view()), name = 'crear_mun'),
    path('crear_cop/',login_required(ProfileCopFormView.as_view()), name = 'crear_cop'),
    path('crear_punt/',login_required(ProfilePuntFormView.as_view()), name = 'crear_punt'),
    ###########Estadisticas de Entidades#################################################
    path('estad_mu/',login_required(post_estad_mu),name = 'estad_mu'),
    path('graf/',login_required(GrafView.as_view()), name = 'graf'),
]

productos/models.py
from django.db import models
from user.models import Entity, UserCustom

class Material(models.Model):
    nombre = models.CharField('Nombre del material', max_length=50)
    descripcion = models.CharField('Breve descripcion del material', max_length=250)

    def __str__(self):
        return self.nombre
        
class MaterialStock(models.Model):
    entity = models.ForeignKey(Entity, on_delete=models.CASCADE, unique = False)
    material = models.ForeignKey(Material, on_delete=models.CASCADE, unique = False)
    peso = models.DecimalField( max_digits=5, decimal_places=2, default = 0)


class Product(models.Model):
    nombre = models.CharField("Nombre de producto", max_length=50)
    descripcion = models.CharField("Descripción de producto", max_length=250, default = '',null = True)
    material = models.ForeignKey(Material, on_delete=models.CASCADE,unique = False)
    cantkg = models.DecimalField(max_digits = 5, decimal_places = 3, default = 0)

    def __str__(self):
        return self.nombre

class ProductStock(models.Model):
    entity = models.ForeignKey(Entity, on_delete=models.CASCADE, unique = False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, unique = False)
    cantidad = models.IntegerField()

class MovPStock(models.Model):
    t_mov = [
        ('EP','Entrada de Producto'),
        ('SP', 'Salida de Producto'),
    ]
    entity = models.ForeignKey(Entity, on_delete=models.CASCADE)
    usuario = models.ForeignKey( UserCustom, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    peso = models.IntegerField()
    tipo = models.CharField(choices= t_mov, max_length=2)
    fecha = models.DateTimeField( auto_now=False, auto_now_add=True)

class MovMStock(models.Model):
    t_mov = [
        ('EM','Entrada de Material'),
        ('SM', 'Salida de Material'),
    ]
    entity = models.ForeignKey(Entity, on_delete=models.CASCADE)
    usuario = models.ForeignKey( UserCustom, on_delete=models.CASCADE)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    peso = models.IntegerField()
    tipo = models.CharField(choices= t_mov, max_length=2)
    fecha = models.DateTimeField( auto_now=False, auto_now_add=True)


class SendProduct(models.Model):
    entity = models.ForeignKey(Entity, on_delete=models.CASCADE, blank=False, null = False)
    product = models.OneToOneField(Product, on_delete=models.CASCADE, blank=False, null = False)
    cant = models.IntegerField()
    date_env = models.DateTimeField( auto_now=False, auto_now_add=True)
    date_recp = models.DateField(auto_now=True, auto_now_add=False)
    recp = models.BooleanField(default=False)

class SendMaterial(models.Model):
    entity = models.ForeignKey(Entity, on_delete=models.CASCADE, blank=False, null = False)
    product = models.OneToOneField(Product, on_delete=models.CASCADE, blank=False, null = False)
    cant = models.IntegerField()
    date_env = models.DateTimeField(auto_now=False, auto_now_add=True)
    date_recp = models.DateField(auto_now=True, auto_now_add=False)
    recp = models.BooleanField(default = False)

user/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import UserCustom, Entity, ProfileCop, ProfileMun, ProfilePunt
from django.contrib.auth.forms import UserCreationForm


class UserForm(UserCreationForm):
    class Meta:
        model = UserCustom
        fields = ['username','email']
class UserAdminForm(forms.ModelForm):
    password1 = forms.CharField(label = 'Contraseña', widget = forms.PasswordInput(
        attrs={
            'class':'form-control',
            'placeholder':'Introduzca contraseña',
            'id':'password1',
            'required':'required',
        }
    ))
    password2 = forms.CharField(label = 'Contraseña de confirmación', widget = forms.PasswordInput(
        attrs={
            'class':'form-control',
            'placeholder':'Vuelva a ingresar su contraseña',
            'id':'password2',
            'required':'required',
        }
    ))
    class Meta:
        model = UserCustom
        fields = ['username','email','first_name','last_name','entity']
        widgets = {
            'username':forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Ingrese el nombre de usuario',
                    'id':'username',
                    'required':'required',
                }
            ),
            'email': forms.EmailInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Ingrese el correo electonico',
                    'id':'email',
                    'required':'required',
                }
            ),
            'first_name':forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Ingrese el nombre',
                    'id':'first_name',
                }
            ),
            'last_name':forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Ingrese el apellido',
                    'id':'last_name',
                }
            ),
            'entity':forms.Select(
                attrs={
                    'class':'form-control',
                    'placeholder':'Ingrese el nombre de usuario',
                    'id':'username',
                    'required':'required',
                }
            ),
        }
        label = {
            'username':_('Nombre de usuario'),
            'email':_('Correo electroníco'),
            'first_name':_('Nombre'),
            'last_name':_('Apellido'),
        }

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Contraseñas no coinciden')
        return password2
class EntityForm(forms.ModelForm):
    class Meta:
        model = Entity
        fields = '__all__'
class ProfileMunForm(forms.ModelForm):
    
    class Meta:
        model = ProfileMun
        fields = '__all__'
class ProfileCopForm(forms.ModelForm):
    
    class Meta:
        model = ProfileCop
        fields = '__all__'
class ProfilePuntForm(forms.ModelForm):
    
    class Meta:
        model = ProfilePunt
        fields = '__all__'

user/views.py
from decimal import Decimal
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, TemplateView
from .forms import UserForm, UserAdminForm, EntityForm, ProfileCopForm, ProfileMunForm, ProfilePuntForm
from .models import UserCustom, Entity, ProfileCop, ProfileMun, ProfilePunt
from django.urls import reverse_lazy


class RegUserEntity(CreateView):
    model = UserCustom
    template_name = 'users/crear_usuario.html'
    form_class = UserForm
    success_url = reverse_lazy('index')

    def post(self, request,*args, **kwargs):
        form = self.form_class(request.POST)
        userlog = UserCustom.objects.get(id = request.user.id)
        if form.is_valid():
            new_user = UserCustom(
                username = form.cleaned_data.get('username'),
                email = form.cleaned_data.get('email'),
                is_user_entity = True,
                entity_id = userlog.entity_id
            )
            new_user.set_password(form.cleaned_data.get('password1'))
            new_user.save()
            return redirect('home')
        else:
            return render(request,self.template_name,{'form':form} )

class RegAdmin(CreateView):
    model = UserCustom
    template_name = 'users/crear_usuario.html'
    form_class = UserAdminForm
    success_url = reverse_lazy('index')
    
    def post(self, request,*args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_user = UserCustom(
                username = form.cleaned_data.get('username'),
                email = form.cleaned_data.get('email'),
                is_admin_entity = True,
                entity_id = form.cleaned_data.get('entity').id
            )
            new_user.set_password(form.cleaned_data.get('password1'))
            new_user.save()
            return redirect('home')
        else:
            return render(request,self.template_name,{'form':form} )

class RegEntity(CreateView):
    model = Entity
    template_name = 'users/crear_entidad.html'
    form_class = EntityForm
    success_url = reverse_lazy('home')
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            if form.cleaned_data.get('tipo') == 'MU':
                form.save()
                return redirect('crear_mun')
            elif form.cleaned_data.get('tipo') == 'CO':
                form.save()
                return redirect('crear_cop')
            elif form.cleaned_data.get('tipo') == 'PL':
                form.save
                return redirect('crear_punt')
        else:
            return render(request,self.template_name,{'form':form})
class ListEntity(ListView):
    model = Entity
    template_name = 'listarentidad.html'

class ListEntityUser(ListView):
    model = Entity
    template_name = 'users/entidades-user.html'

class HomeUserView(TemplateView):
    template_name = "users/home-user.html"

def HomeUserView2(request):
    userlog = UserCustom.objects.get(id = request.user.id)
    entity = Entity.objects.get(id = userlog.entity_id)

    return render(request, 'users/home-user.html',{'entity':entity,'userlog':userlog})
class ProfileMunFormView(CreateView):
    model = ProfileMun
    template_name = "users/mun.html"
    form_class = ProfileMunForm
    success_url = reverse_lazy('home')

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            ent = Entity.objects.latest('id')
            mun = ProfileMun(
                mun_id = ent.id,
                hab = form.cleaned_data.get('hab'),
                dispo_final = form.cleaned_data.get('dispo_final'),
                difreco = form.cleaned_data.get('difreco'),
                complejo_tratamiento = form.cleaned_data.get('complejo_tratamiento'),
                compostaje_biodigestion = form.cleaned_data.get('compostaje_biodigestion'),
                planta_clasif = form.cleaned_data.get('planta_clasif'),
                otros = form.cleaned_data.get('otros'),
                ton_recup = form.cleaned_data.get('ton_recup'),
                pers_recol = form.cleaned_data.get('pers_recol'),
                pers_comp_am = form.cleaned_data.get('pers_comp_am'),
                ton_proces = form.cleaned_data.get('ton_proces'),
                cost_recol = form.cleaned_data.get('cost_recol'),
                cost_comp_am = form.cleaned_data.get('cost_comp_am'),
                ing_venta = form.cleaned_data.get('ing_venta'),
            )
            mun.save()
            return redirect('crear_entity')
        else:
            return render(request,self.template_name,{'form':form})


class ProfileCopFormView(CreateView):
    model = ProfileCop
    template_name = "users/cop.html"
    form_class = ProfileCopForm
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            cop = ProfileCop(
                cop_id = Entity.objects.latest('id').id,
                cant_socio = form.cleaned_data.get('cant_socio'),
                fuent_rec = form.cleaned_data.get('fuent_rec'),
                recol = form.cleaned_data.get('recol'),
                empl = form.cleaned_data.get('empl'),
                ton_rec = form.cleaned_data.get('ton_rec'),
                ton_a_rechazo = form.cleaned_data.get('ton_a_rechazo'),
                gast_totales = form.cleaned_data.get('gast_totales'),
            )
            cop.save()
            return redirect('crear_entity')
        else:
            return render(request,self.template_name,{'form':form})

class ProfilePuntFormView(CreateView):
    model = ProfilePunt
    template_name = "users/punt.html"
    form_class = ProfilePuntForm

    def post(self, request, *args, **kwargs):
        form = form = self.form_class(request.POST)
        if form.is_valid():
            punt = ProfilePunt(
                punt_id = Entity.objects.latest('id').id,
                propiedad = form.cleaned_data.get('propiedad'),
                operacion = form.cleaned_data.get('operacion'),
                ton_recup = form.cleaned_data.get('ton_recup'),
                visitas = form.cleaned_data.get('visitas'),
                gast_op = form.cleaned_data.get('gast_op'),
                cant_personas = form.cleaned_data.get('cant_personas'),
            )
            punt.save()
            return redirect('crear_entity')
        else:
            return render(request,self.template_name,{'form':form})

def post_estad_mu(request):
    userlog = UserCustom.objects.get(id = request.user.id)
    entity = Entity.objects.get(id = userlog.entity_id)
    if entity.tipo == 'MU':
        mu = ProfileMun.objects.get(mun_id = entity.id)
        
        mu_indc_prud = mu.ton_recup / mu.pers_clas /12
        mu_indc_prud = round(mu_indc_prud,2)
        
        mu_indc_lab = (mu.pers_recol + mu.pers_comp_am)/ ( mu.hab * 0.001)
        mu_indc_lab = round(mu_indc_lab,2)
        
        mu_girsu = 0
        
        mu_indc_rec = Decimal(mu.ton_recup) *Decimal( 1000.00)/ Decimal(mu.hab)
        mu_indc_rec = round(mu_indc_rec,2)
        return render(request,'users/estad_mu.html',{'mu':mu,'mu_indc_prud':mu_indc_prud,'mu_indc_lab':mu_indc_lab,'mu_indc_rec':mu_indc_rec})
    elif entity.tipo == 'CO':
        cop = ProfileCop.objects.get(cop_id = entity.id)

        cop_indc_prud = cop.ton_rec / cop.empl /12
        cop_indc_prud = round(cop_indc_prud,2)

        cop_girsu = cop.gast_totales / cop.ton_rec
        cop_girsu = round(cop_girsu,2)

        cop_ind_rec = cop.ton_a_rechazo/cop.ton_rec -1
        return render(request,'users/estad_cop.html',{'cop':cop,'cop_indc_prud':cop_indc_prud,'cop_girsu':cop_girsu,'cop_ind_rec':cop_ind_rec})

    elif entity.tipo == 'PL':
        pl = ProfilePunt(punt_id = entity.id)

        pl_indc_prud = pl.ton_recup / pl.cant_personas /12

        pl_girsu = 0

        pl_indc_rec = 0

        return render(request,'users/estad_pl.html',{'pl':pl,'pl_indc_prud':pl_indc_prud,'pl_girsu':pl_girsu,'pl_indc_rec':pl_indc_rec})

class GrafView(TemplateView):
    template_name = 'users/graf.html'

templates/users/cop.html
{% extends 'users/home-user.html' %}
{% block title %}registro de municipio{% endblock title %}


{% block body %}
    <div class="container" style="padding : 5%">
        <div class="card">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class = "btn btn-primary">Resgistrar</button>
            </form>
            
            
        </div>
        
        
    </div>
{% endblock body %}

templates/users/crear_entidad.html
{% extends 'users/home-user.html' %}
{% block title %}registro de usuarios{% endblock title %}


{% block body %}
    <div class="container" style="padding : 5%">
        <div class="card">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class = "btn btn-primary">Resgistrar</button>
            </form>
        </div>   
    </div>
{% endblock body %}
    

templates/users/crear_usuario.html
{% extends 'users/home-user.html' %}
{% block title %}registro de usuarios{% endblock title %}


{% block body %}
{% if perms.user.can_add_user %}
    <div class="container" style="padding : 5%">
        <div class="card">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class = "btn btn-primary">Resgistrar</button>
            </form>
        </div>
    </div>
{% else %}
    <div class="container">
        <h1>No tiene Permisos de Acceso</h1>
    </div>
{% endif %}
{% endblock body %}
    

templates/users/entidades-user.html
{% extends 'users/home-user.html' %}
{% block title %}Entidades{% endblock title %}
    


{% block body %}
    {% if object_list %}
        <div class="container" style="padding:5%">
            <div class="card">
                <div class="card-header text-ligth" style = "background:#9fedd4;">
                    <strong class="card-title"><h1 class="text-center">Listado de Entendidades</h1></strong>
                </div>
                <div class="table-stats order-table ov-h">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nombre de Entendidad</th>
                                <th>País</th>
                                <th>Tipo</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for entidad in object_list %}
                                <tr>
                                    <td>{{ entidad.id }}</td>
                                    <td>{{ entidad.nombre }}</td>
                                    <td>{{ entidad.pais }}</td>
                                    <td>{{ entidad.tipo }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock body %}

templates/users/estad_cop.html
{% extends 'users/home-user.html' %}
{% block title %}Entidades{% endblock title %}
    



{% block body %}
    <div class="container" style="padding: 5% 0;">
        <div class="col">
            <div class="row-sm-5">
                <div class="card text-center">
                    <div class="card-header" style="background-color: #ddf6dd;">
                        <h5>Indice de Productividad : {{cop_indc_prud}} </h5>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Parametros estadisticos relavantes</h5>
                        <p class="card-text">Toneladas recuperadas para reciclado por año : {{cop.ton_rec}}</p>
                        <p class="card-text">Cantidad de empleados : {{cop.empl}} </p>
                    </div>
                </div>
            </div>
                <div class="row-sm-5">
                    <div class="card text-center">
                        <div class="card-header" style="background-color: #ddf6dd;">
                            <h5>Indice costos GIRSU: {{cop_girsu}} </h5>
                        </div>
                        <h5 class="card-title">Parametros estadisticos relevantes</h5>
                        <p class="card-text">Toneladas Recuperada para reciclado por año: {{cop.ton_rec}} </p>
                        <p class="card-text">Gastos totales operativos en dolares: {{cop.gast_totales}} </p>
                    </div>
                </div>
                <div class="row-sm-5">
                    <div class="card text-center">
                        <div class="card-header" style="background-color: #ddf6dd;">
                            <h5>Indice de Reciclaje por habitante: {{cop_ind_rec}} </h5>
                        </div>
                        <h5 class="card-title">Parametros estadisticos relevantes</h5>
                        <p class="card-text">Toneladas recuperadas para reciclado: {{cop.ton_rec}} </p>
                        <p class="card-text">Toneladas a rechazo por año: {{cop.ton_a_rechazo}} </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

templates/users/estad_pl.html
{% extends 'users/home-user.html' %}
{% block title %}Entidades{% endblock title %}
    



{% block body %}
    <div class="container" style="padding: 10% 0;">
        <div class="col">
            <div class="row-sm-5">
                <div class="card text-center">
                    <div class="card-header" style="background-color: #ddf6dd;">
                        <h5>Indice de Productividad : {{pl_indc_prud}} </h5>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Parametros estadisticos relavantes</h5>
                        <p class="card-text">Toneladas recuperadas para reciclado por año : {{pl.ton_recup}}</p>
                        <p class="card-text">Cantidad de personas : {{pl.cant_personas}} </p>
                    </div>
                </div>
            </div>
    
        </div>
        <div class = "container" style="padding: 10% 0;">
                <div class="row-sm-5">
                    <div class="card text-center">
                        <div class="card-header" style="background-color: #ddf6dd;">
                            <h5>Indice costos GIRSU: {{pl_girsu}} </h5>
                        </div>
                        <h5 class="card-title">Parametros estadisticos relevantes</h5>
                        <p class="card-text">Toneladas Recuperada para reciclado por año: {{pl.ton_recup}} </p>
                        <p class="card-text">Gastos totales operativos en dolares: {{pl.gast_op}} </p>
                    </div>
                </div>
            </div>
            <div class = "container" style="padding: 10% 0;">
                <div class="row-sm-5">
                    <div class="card text-center">
                        <div class="card-header" style="background-color: #ddf6dd;">
                            <h5>Indice de Reciclaje por habitante: {{pl_indc_rec}} </h5>
                        </div>
                        <h5 class="card-title">Parametros estadisticos relevantes</h5>
                        <p class="card-text">Toneladas recuperadas para reciclado: {{cop.ton_rec}} </p>
                        <p class="card-text">Toneladas a rechazo por año: {{cop.ton_a_rechazo}} </p>
                    </div>
                </div>
            </div>
    </div>

templates/users/home-user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href= " {% static "css/style.css" %}" >
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400&display=swap" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.js" integrity="sha512-QEiC894KVkN9Tsoi6+mKf8HaCLJvyA6QIRzY5KrfINXYuP9NxdIkRQhGq3BZi0J4I7V5SidGM3XUQ5wFiMDuWg==" crossorigin="anonymous"></script>
    <title>
    {% block title %}
        index
    {% endblock title %}
    </title>
</head>
<body>
    
    {% block nav %}    
    <nav class = "navbar navbar-expand-lg navbar-dark" style="background-color: #4b8a4b;">
        <a href="{% url 'home' %}" class="navbar-brand">
            Economia
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarIndex" >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarIndex">
            <ul class = "navbar-nav mr-auto ">
                
                {% if perms.productos.view_product %}
                <li>
                    <div class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style= "color:#ffff">
                            Productos
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'list-prod' %}">Ver productos</a>
                        <a class="dropdown-item" href = "{% url 'reg-prod' %}">Cargar producto</a>
                        <a class="dropdown-item" href = "{% url 'ing_stock_prod' %}">Cargar producto al stock</a>
                        <a class="dropdown-item" href = "{% url 'prod_stock' %}">Ver stock de productos</a>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style= "color:#ffff">
                            Materiales
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'mat' %}">Ver materiales</a>
                        <a class="dropdown-item" href="{% url 'reg_mat' %}">Registrar material</a>
                        <a class="dropdown-item" href = "{% url 'ing_stock_mat' %}">Cargar material al stock</a>
                        <a class="dropdown-item" href = "{% url 'mat_stock' %}">Ver materiales en stock</a>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style= "color:#ffff">
                            Gestion entidad
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'estad_mu' %}">Indicadores</a>
                        <a class="dropdown-item" href="{% url 'entidades-user' %}" class="nav-link">Entidades</a>
                        {% if perms.user.is_admin_entity %}
                            <a href="{% url 'crear_user' %}" class="nav-link">Crear Usuario</a>
                        {% endif %}
                        
                        {% if user.is_superuser %}
                            <a href="url 'crear_entity' %}" ></a>
                            
                        {% endif %}
                            
                        </div>
                    </div>
                </li>
                {% endif %}
                
                {% if user.is_superuser %}
                <li>
                    <div class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style= "color:#ffff">
                            Gestion de Usuarios
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'crear_admin' %}">Registrar un administrador de entidad</a>
                        <a class="dropdown-item" href = "{% url 'crear_user' %}">Resgistrar un usuario de entidad</a>
                        </div>
                    </div>
                </li>
                {% endif %}
                <li class="nav-item active">
                    <a href="{% url 'logout' %}" class="nav-link">Cerrar Sesión({{user.username}})</a>
                </li>
            </ul>
        </div>
    </nav>
    {% endblock nav %}
        
    {% block body %}
        <div class="container" style="padding: 10% 0;" >
            <div class="container" style="padding: 10% 10%; background-color: #ddf6dd" >
                <h1>Bienvenido {{user.username}} </h1>
                <p>Esta operando como 
                    
                    {% if user.is_admin_entity %}
                        Adiministrador {{ entity.nombre }}
                    {% elif user.is_superuser %}
                        Super Usuario
                    {% else %}
                        Usuario 
                    {% endif %}
                        
                </p>
            </div>
            
        </div>
    {% endblock body %}
</body>
</html>

templates/users/mun.html
{% extends 'users/home-user.html' %}
{% block title %}registro de municipio{% endblock title %}


{% block body %}
    <div class="container" style="padding : 5%">
        <div class="card">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class = "btn btn-primary">Resgistrar</button>
            </form>
            
            
        </div>
        
        
    </div>
{% endblock body %}
    